In [1]:
import numpy as np
import pandas as pd
from subprocess import check_output

In [2]:
diff=pd.read_csv('https://raw.githubusercontent.com/Varun2063/disease-diagnoser-and-drug-recommender/main/data/diffsydiw.csv')
sym=pd.read_csv('https://raw.githubusercontent.com/Varun2063/disease-diagnoser-and-drug-recommender/main/data/sym_t.csv')
dia=pd.read_csv('https://raw.githubusercontent.com/Varun2063/disease-diagnoser-and-drug-recommender/main/data/dia_t.csv')

In [3]:
diff

syd    did  wei
0       1.0  163.0  2.0
1       1.0  164.0  2.0
2       1.0  165.0  1.0
3       1.0  187.0  2.0
4       1.0  306.0  2.0
...     ...    ...  ...
5564  261.0  752.0  0.0
5565  282.0  277.0  0.0
5566  290.0  509.0  1.0
5567  272.0  188.0  2.0
5568    NaN    NaN  NaN

[5569 rows x 3 columns]

In [4]:
sym

syd                          symptom
0      1             Upper abdominal pain
1      2             Lower abdominal pain
2      3      Abscess (Collection of pus)
3      4                    Alcohol abuse
4      5            Anxiety (Nervousness)
..   ...                              ...
267  295                 Nipple discharge
268  301  Shoulder stiffness or tightness
269  303       Arm stiffness or tightness
270  304              High blood pressure
271  306                 High blood sugar

[272 rows x 2 columns]

In [5]:
sym = sym.dropna()

In [6]:
symptoms = sym['symptom'].tolist()

In [7]:
dia

did                                           diagnose
0        1  Abdominal aortic aneurysm
(enlarged major bloo...
1        2                                 Abdominal swelling
2        3                                   Abdominal trauma
3        4                               Abrasions
 (scrapes)
4        5  ACE inhibitor induced cough
blood pressure med...
...    ...                                                ...
1161  1529                      Triple negative breast cancer
1162  1531                          Invasive ductal carcinoma
1163  1533                         Invasive lobular carcinoma
1164  1535                                           Dystonia
1165  1537        Failure to thrive - adult
failure to thrive

[1166 rows x 2 columns]

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/Varun2063/disease-diagnoser-and-drug-recommender/main/data/dia_t.csv")
df = df['diagnose'].str.split('\x0b', expand=True).merge(df, right_index=True, left_index=True).drop(columns=['diagnose'])
df.columns = [f'diagnose_{i+1}' for i in range(len(df.columns))]
df = df[["diagnose_6", "diagnose_1", "diagnose_2", "diagnose_3", "diagnose_4", "diagnose_5"]]
df.columns = ["did","diagnosis","cause_1", "cause_2", "cause_3", "cause_4"]
dia_t = df

In [9]:
dia_t.columns

Index(['did', 'diagnosis', 'cause_1', 'cause_2', 'cause_3', 'cause_4'], dtype='object')

In [10]:
dia

did                                           diagnose
0        1  Abdominal aortic aneurysm
(enlarged major bloo...
1        2                                 Abdominal swelling
2        3                                   Abdominal trauma
3        4                               Abrasions
 (scrapes)
4        5  ACE inhibitor induced cough
blood pressure med...
...    ...                                                ...
1161  1529                      Triple negative breast cancer
1162  1531                          Invasive ductal carcinoma
1163  1533                         Invasive lobular carcinoma
1164  1535                                           Dystonia
1165  1537        Failure to thrive - adult
failure to thrive

[1166 rows x 2 columns]

In [11]:
dia_t

did                      diagnosis  \
0        1      Abdominal aortic aneurysm   
1        2             Abdominal swelling   
2        3               Abdominal trauma   
3        4                      Abrasions   
4        5    ACE inhibitor induced cough   
...    ...                            ...   
1161  1529  Triple negative breast cancer   
1162  1531      Invasive ductal carcinoma   
1163  1533     Invasive lobular carcinoma   
1164  1535                       Dystonia   
1165  1537      Failure to thrive - adult   

                                    cause_1             cause_2  \
0             (enlarged major blood vessel)                None   
1                                      None                None   
2                                      None                None   
3                                 (scrapes)                None   
4     blood pressure medication side effect  Drug-induced cough   
...                                     ...                 ...   
1161                                   None                None   
1162                                   None                None   
1163                                   None                None   
1164                                   None                None   
1165                      failure to thrive                None   

                           cause_3 cause_4  
0                             None    None  
1                             None    None  
2                             None    None  
3                             None    None  
4     Drug reaction: ACE inhibitor    None  
...                            ...     ...  
1161                          None    None  
1162                          None    None  
1163                          None    None  
1164                          None    None  
1165                          None    None  

[1166 rows x 6 columns]

In [12]:
#dia_t.drop(index=dia_t.index[-1],axis=0,inplace=True)

In [13]:
len(dia.did.unique())

1166

In [14]:
sd_diff=diff.merge(sym, left_on='syd', right_on='syd')

In [15]:
sd_diff.head()

syd    did  wei               symptom
0  1.0  163.0  2.0  Upper abdominal pain
1  1.0  164.0  2.0  Upper abdominal pain
2  1.0  165.0  1.0  Upper abdominal pain
3  1.0  187.0  2.0  Upper abdominal pain
4  1.0  306.0  2.0  Upper abdominal pain

In [16]:
dia_t['did'] = dia_t['did'].astype('float')

In [17]:
dia_t.columns

Index(['did', 'diagnosis', 'cause_1', 'cause_2', 'cause_3', 'cause_4'], dtype='object')

In [18]:
len(dia_t)

1166

In [19]:
sd_diff=sd_diff.merge(dia_t[['did', 'diagnosis']], left_on='did', right_on='did')

In [20]:
sd_diff

syd     did  wei                         symptom  \
0       1.0   163.0  2.0            Upper abdominal pain   
1       2.0   163.0  1.0            Lower abdominal pain   
2       7.0   163.0  1.0               Back ache or pain   
3      29.0   163.0  2.0                           Fever   
4      32.0   163.0  1.0                      Flank pain   
...     ...     ...  ...                             ...   
5199  272.0  1170.0  2.0                      Skin bumps   
5200  272.0  1184.0  0.0                      Skin bumps   
5201  272.0  1186.0  0.0                      Skin bumps   
5202  272.0   899.0  0.0                      Skin bumps   
5203  277.0   650.0  0.0  Unusual color or odor of urine   

                             diagnosis  
0                        Cholecystitis  
1                        Cholecystitis  
2                        Cholecystitis  
3                        Cholecystitis  
4                        Cholecystitis  
...                                ...  
5199                    Viral exanthem  
5200                 Actinic keratosis  
5201             Molluscum contagiosum  
5202                 Keratosis pilaris  
5203  Renal arteriovenous malformation  

[5204 rows x 5 columns]

In [21]:
diff

syd    did  wei
0       1.0  163.0  2.0
1       1.0  164.0  2.0
2       1.0  165.0  1.0
3       1.0  187.0  2.0
4       1.0  306.0  2.0
...     ...    ...  ...
5564  261.0  752.0  0.0
5565  282.0  277.0  0.0
5566  290.0  509.0  1.0
5567  272.0  188.0  2.0
5568    NaN    NaN  NaN

[5569 rows x 3 columns]

In [22]:
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm
from scipy.sparse import coo_matrix, csr_matrix

def read_data(filename):

    data = pd.read_csv(filename)
    data=data.dropna(axis=0, how='any')
    data['syd'] = data['syd'].astype("category")
    data['did'] = data['did'].astype("category")
    matrix = coo_matrix((data['wei'].astype(float),
                        (data['did'].cat.codes.copy(),
                         data['syd'].cat.codes.copy())))
    return data, matrix,data.groupby(['did']).wei.sum(),data['syd'].cat.codes.copy()

data,matrix,diagnosis,symptoms=read_data('https://raw.githubusercontent.com/Varun2063/disease-diagnoser-and-drug-recommender/main/data/diffsydiw.csv')

In [23]:
print(matrix)

  (151, 0)	2.0
  (152, 0)	2.0
  (153, 0)	1.0
  (175, 0)	2.0
  (286, 0)	2.0
  (287, 0)	1.0
  (288, 0)	2.0
  (289, 0)	2.0
  (331, 0)	1.0
  (369, 0)	1.0
  (377, 0)	1.0
  (468, 0)	1.0
  (498, 0)	2.0
  (654, 0)	1.0
  (50, 1)	3.0
  (167, 1)	2.0
  (224, 1)	1.0
  (359, 1)	2.0
  (491, 1)	1.0
  (492, 1)	1.0
  (507, 1)	1.0
  (548, 1)	1.0
  (721, 1)	2.0
  (723, 1)	1.0
  (39, 2)	1.0
  :	:
  (1, 260)	1.0
  (118, 258)	2.0
  (391, 258)	0.0
  (141, 262)	0.0
  (264, 250)	0.0
  (547, 259)	0.0
  (187, 259)	0.0
  (659, 259)	1.0
  (658, 259)	0.0
  (940, 254)	0.0
  (684, 251)	1.0
  (809, 251)	3.0
  (896, 251)	1.0
  (300, 251)	1.0
  (445, 251)	1.0
  (95, 251)	1.0
  (962, 251)	0.0
  (264, 251)	0.0
  (844, 269)	1.0
  (563, 254)	1.0
  (560, 245)	0.0
  (683, 245)	0.0
  (262, 259)	0.0
  (464, 262)	1.0
  (176, 253)	2.0


In [24]:
symptoms

0         0
1         0
2         0
3         0
4         0
       ... 
5563    245
5564    245
5565    259
5566    262
5567    253
Length: 5371, dtype: int16

In [25]:
def print_csrmatrix(matrix):
  matrix_df = pd.DataFrame({'Row': matrix.row, 'Column': matrix.col, 'Value': matrix.data})
  matrix_df.drop_duplicates(['Row', 'Column'], inplace = True)
  matrix_df_pivoted = matrix_df.pivot(index='Row', columns='Column', values='Value')
  coo_df_pivoted = matrix_df.fillna(0)
  return coo_df_pivoted

In [26]:
print(matrix.row)

[151 152 153 ... 262 464 176]


In [27]:
print(matrix.col)

[  0   0   0 ... 259 262 253]


In [28]:
print(matrix.data)

[2. 2. 1. ... 0. 1. 2.]


In [29]:
matrix_print = print_csrmatrix(matrix)

In [30]:
matrix_print

Row  Column  Value
0     151       0    2.0
1     152       0    2.0
2     153       0    1.0
3     175       0    2.0
4     286       0    2.0
...   ...     ...    ...
5366  560     245    0.0
5367  683     245    0.0
5368  262     259    0.0
5369  464     262    1.0
5370  176     253    2.0

[5352 rows x 3 columns]

In [31]:
print(matrix_print.equals(diff))

False


In [32]:
matrix_print = print_csrmatrix(matrix)
np.sort(matrix_print.Row.unique())

array([   0,    1,    2, ..., 1142, 1143, 1144], dtype=int32)

In [33]:
from sklearn.preprocessing import normalize


def bm25_weight(data, K1=1.2, B=0.8):
    """ Weighs each row of the matrix data by BM25 weighting """
    # calculate idf per term (user)
    N = float(data.shape[0])
    idf = np.log(N / (1 + np.bincount(data.col)))

    # calculate length_norm per document (artist)
    row_sums = np.squeeze(np.asarray(data.sum(1)))
    average_length = row_sums.sum() / N
    length_norm = (1.0 - B) + B * row_sums / average_length

    # weight matrix rows by bm25
    ret = coo_matrix(data)
    ret.data = ret.data * (K1 + 1.0) / (K1 * length_norm[ret.row] + ret.data) * idf[ret.col]
    return ret



user_count = data.groupby('syd').size()

similarity = bm25_weight(matrix)

In [34]:
sym[sym['syd'].isin(list(diagnosis.index))]

syd                      symptom
0      1         Upper abdominal pain
1      2         Lower abdominal pain
2      3  Abscess (Collection of pus)
3      4                Alcohol abuse
4      5        Anxiety (Nervousness)
..   ...                          ...
266  294       Confusion and headache
267  295             Nipple discharge
269  303   Arm stiffness or tightness
270  304          High blood pressure
271  306             High blood sugar

[232 rows x 2 columns]

In [35]:
from scipy.sparse.linalg import svds

Ur, Si, VTr = svds(bm25_weight(coo_matrix(matrix)), k=100)
print(Ur.shape, Si.shape, VTr.shape,symptoms.shape,matrix.shape,data.shape,diagnosis.shape,user_count.shape)

(1145, 100) (100,) (100, 272) (5371,) (1145, 272) (5371, 3) (1145,) (272,)


In [36]:
VTr1 = pd.DataFrame(VTr)
VTr1

0         1         2         3         4         5         6    \
0   0.044759  0.007424  0.018030  0.126188 -0.034513 -0.024845  0.093172   
1  -0.054806 -0.115467 -0.001820 -0.047810  0.038813 -0.012854 -0.054173   
2   0.020929 -0.050410 -0.000280 -0.003373 -0.014557 -0.004425  0.133057   
3   0.038277 -0.033979  0.057405 -0.017114 -0.003032  0.032557  0.007060   
4  -0.052237 -0.001196  0.056222  0.018460  0.047148 -0.006409 -0.014069   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.049713 -0.084552  0.004101 -0.003033  0.019033  0.017308 -0.012530   
96 -0.064279 -0.042335  0.047547 -0.010146 -0.010958  0.037288  0.003923   
97  0.122013  0.079299  0.013020  0.001809 -0.002172  0.031884  0.059914   
98  0.038626  0.028567  0.025563  0.019936  0.019750  0.020199  0.034406   
99  0.054985  0.039201  0.042784  0.030622  0.029117  0.027007  0.045429   

         7         8         9    ...       262       263       264       265  \
0  -0.000035  0.010131  0.076973  ... -0.044562  0.009739 -0.034098 -0.034901   
1   0.066661  0.025943 -0.071231  ... -0.013393 -0.009527  0.047974 -0.033756   
2  -0.024895 -0.061530 -0.045256  ... -0.048006 -0.035837  0.045479 -0.009719   
3   0.008798 -0.034905 -0.023030  ... -0.103760  0.002417 -0.138713  0.052093   
4  -0.030588 -0.061811  0.040662  ... -0.000074  0.044171 -0.041867  0.037310   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95 -0.051824 -0.066873 -0.304937  ...  0.000814  0.002998  0.063597 -0.025650   
96 -0.016230 -0.041189 -0.114516  ...  0.025450  0.002897 -0.046819  0.017069   
97  0.035591  0.039360  0.137135  ...  0.004430 -0.019300 -0.115177 -0.189635   
98  0.016305 -0.026182  0.039056  ...  0.014902  0.022979  0.137480  0.112803   
99  0.023205  0.053678  0.053853  ...  0.021733  0.032520  0.207124  0.154543   

         266       267       268       269       270       271  
0   0.041835 -0.001003  0.023759  0.002629  0.054431 -0.003595  
1  -0.032077 -0.002357 -0.050076 -0.040714 -0.064462 -0.256881  
2  -0.010340 -0.001683 -0.012460 -0.020713  0.026987 -0.040113  
3  -0.016570  0.034879 -0.100466 -0.080672  0.102815 -0.044973  
4  -0.018091 -0.006925  0.046652  0.018102  0.079962 -0.005850  
..       ...       ...       ...       ...       ...       ...  
95 -0.037364  0.022136  0.007809  0.006620  0.012124 -0.005706  
96 -0.022698 -0.001147  0.030493  0.031003 -0.009133 -0.001261  
97 -0.236128  0.027145  0.016178  0.015676 -0.023078  0.005500  
98  0.146269  0.010857  0.009017  0.008755  0.033290  0.015496  
99  0.196954  0.016231  0.010849  0.011057  0.045367  0.021790  

[100 rows x 272 columns]

In [37]:
Ur1 = pd.DataFrame(Ur)
Ur1

0         1         2         3         4         5         6   \
0    -0.008968  0.042104  0.086998  0.007656 -0.012864 -0.051140 -0.007296   
1     0.002728  0.016621 -0.008143 -0.002540 -0.005266 -0.000451  0.013840   
2     0.014596 -0.130509  0.022759  0.025989  0.022206  0.038083 -0.006608   
3     0.032694 -0.035970 -0.008614  0.013213  0.130591 -0.105418 -0.027835   
4    -0.044936  0.032702 -0.050693  0.010328 -0.049051 -0.041319  0.044163   
...        ...       ...       ...       ...       ...       ...       ...   
1140  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1141  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1142  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1143  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1144 -0.016079  0.022349  0.019648 -0.037975 -0.000863  0.005276 -0.011763   

            7         8         9   ...        90        91        92  \
0    -0.032212  0.002630  0.059533  ...  0.034701  0.005139 -0.061434   
1     0.011995  0.009432 -0.003544  ... -0.004948 -0.000277 -0.007262   
2     0.001341  0.022561  0.008799  ...  0.021183  0.001854 -0.018453   
3    -0.011934  0.126886 -0.077518  ...  0.004745 -0.024272  0.002164   
4    -0.043299 -0.030304 -0.055430  ... -0.001324 -0.004090  0.026858   
...        ...       ...       ...  ...       ...       ...       ...   
1140  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
1141  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
1142  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
1143  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
1144 -0.005204 -0.020582 -0.016172  ... -0.044565 -0.006921 -0.028179   

            93        94        95        96        97        98        99  
0    -0.026522  0.028150 -0.018778 -0.012962  0.038270  0.014734  0.021451  
1    -0.000224  0.001312  0.000664 -0.001364  0.003443  0.001913  0.003217  
2    -0.020718  0.006447 -0.008222 -0.004370  0.009840  0.004877  0.010312  
3     0.000940 -0.000871 -0.004971  0.038969  0.011430  0.002611  0.006013  
4    -0.042353 -0.038264  0.005104  0.035021  0.029089  0.010683  0.017417  
...        ...       ...       ...       ...       ...       ...       ...  
1140  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1141  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1142  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1143  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1144  0.015781 -0.004825  0.010565 -0.007908 -0.016918  0.019542  0.028077  

[1145 rows x 100 columns]

In [38]:
Si1 = pd.DataFrame(Si)
Si1

0
0   15.163773
1   15.200634
2   15.404991
3   15.458354
4   15.532451
..        ...
95  29.759765
96  30.145436
97  31.058471
98  33.508128
99  34.833379

[100 rows x 1 columns]

In [39]:
from sklearn.metrics.pairwise import cosine_similarity
Sddf=pd.DataFrame(cosine_similarity(Ur,VTr.T),columns=user_count.index,index=list(diagnosis.index))
Sddf.to_csv('Sddf.csv')

In [40]:
Sydi=pd.DataFrame(cosine_similarity(Ur,VTr.T))

In [41]:
booknr_list = [10, 11, 13, 24]

disease_scores = {}

for booknr in booknr_list:
    similar_diseases = Sddf[booknr].sort_values(ascending=False).head(7)

    for disease, score in similar_diseases.items():
        if disease in disease_scores:
            disease_scores[disease] += score
        else:
            disease_scores[disease] = score

combined_scores_df = pd.DataFrame(list(disease_scores.items()), columns=['Disease', 'Combined_Score'])

top_related_diseases = combined_scores_df.sort_values(by='Combined_Score', ascending=False).head(7)

for index, row in top_related_diseases.iterrows():
    disease_id = row['Disease']
    combined_score = row['Combined_Score']

    disease_info = dia_t[dia_t['did'] == disease_id]
    disease_name = disease_info['diagnosis'].values[0]
    causes = disease_info[['cause_1', 'cause_2', 'cause_3', 'cause_4']].values.flatten()

    print(f"Disease: {disease_name}, Combined Score: {combined_score}")
    for i, cause in enumerate(causes, start=1):
        if ( cause == None):
          pass
        else:
          print(f"Cause : {cause}")
    print()


Disease: Radiation exposure, Combined Score: 0.9980603602247422
Cause : radiation sickness

Disease: Mastitis, Combined Score: 0.9942798724571605
Cause : breast infection inflammation

Disease: Fibrocystic breasts, Combined Score: 0.9929747217199386
Cause : breast lumpiness

Disease: Breast fibroadenoma, Combined Score: 0.9929747217199386
Cause : benign breast lumps

Disease: Breast abscess, Combined Score: 0.9891016551336791
Cause : collection of pus in the breast

Disease: Cauliflower ear, Combined Score: 0.9871555299305192
Cause : wrestlers ear

Disease: Hemolytic uremic syndrome, Combined Score: 0.9828600680640818
Cause : HUS, red blood cell destruction, kidney disease

